export const DEFAULT_SUBJECT_SUGGESTIONS = ['Kobe Bryant', 'Frida Kahlo', 'Muhammad Ali']

export const SUBJECT_SUGGESTIONS: string[] = [
  // People — Athletes
  'Kobe Bryant',
  'Muhammad Ali',
  'Serena Williams',
  'Michael Jordan',
  'Pelé',
  'Roger Federer',
  'Simone Biles',
  'Usain Bolt',
  // People — Artists & Writers
  'Frida Kahlo',
  'Pablo Picasso',
  'Vincent van Gogh',
  'Leonardo da Vinci',
  'Georgia O\u2019Keeffe',
  'Maya Angelou',
  'Toni Morrison',
  'Ernest Hemingway',
  // People — Scientists
  'Albert Einstein',
  'Marie Curie',
  'Isaac Newton',
  'Charles Darwin',
  'Stephen Hawking',
  'Nikola Tesla',
  'Ada Lovelace',
  'Alan Turing',
  // People — Leaders & Activists
  'Martin Luther King Jr.',
  'Nelson Mandela',
  'Mahatma Gandhi',
  'Abraham Lincoln',
  'Winston Churchill',
  'Malcolm X',
  'Rosa Parks',
  'John F. Kennedy',
  // People — Musicians
  'David Bowie',
  'Prince',
  'Beyoncé',
  'Bob Dylan',
  'The Beatles',
  'Aretha Franklin',
  'Michael Jackson',
  // People — Presidents
  'Barack Obama',
  'Theodore Roosevelt',
  'Franklin D. Roosevelt',
  'George Washington',
  // Events
  'World War II',
  'World War I',
  'The French Revolution',
  'The Cold War',
  'The Apollo 11 Moon Landing',
  'The Fall of the Berlin Wall',
  'The Civil Rights Movement',
  'The American Revolution',
  'The Industrial Revolution',
  // Topics
  'The Renaissance',
  'The Space Race',
  'The History of Jazz',
  'The History of Hip-Hop',
  'The Internet',
  'Climate Change',
  'Artificial Intelligence',
  'Quantum Physics',
  // Organizations
  'Apple Inc.',
  'NASA',
  'Microsoft',
  'Google',
  'Pixar',
  'Nike',
  'The United Nations',
  'SpaceX',
]
